version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: technobre/demo-api
    container_name: demo-api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    networks:
      - demo


  sqlite-web:
    image: coleifer/sqlite-web
    container_name: sqlite-web
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=/data/app.db
    networks:
      - demo


networks:
  demo:
    driver: bridge
